# Generated by Django 3.2.4 on 2021-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='EPS2019Q3',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eps',
            name='EPS2019Q4',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eps',
            name='EPS2020Q1',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eps',
            name='EPS2020Q2',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eps',
            name='EPS2020Q3',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eps',
            name='EPS2020Q4',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eps',
            name='EPS2021Q1',
            field=models.FloatField(blank=True, default='', max_length=200, null=True),
        ),
    ]
