# Generated by Django 3.2.4 on 2021-06-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignInvestorsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('FuturesClosingPrice', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('BuyCall', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('BuyCallChange', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('BuyPut', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('BuyPutChange', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('SellCall', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('SellCallChange', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('SellPut', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('SellPutChange', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('BuyNet', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
                ('SellNet', models.IntegerField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
    ]
