# Generated by Django 3.2.4 on 2021-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForeignInvestorsOption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigninvestorsoption',
            name='BuyOpenPosition',
            field=models.FloatField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foreigninvestorsoption',
            name='Fluctuation',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foreigninvestorsoption',
            name='SellOpenPosition',
            field=models.FloatField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
